defaults:
  - _self_
  - hydra: default
  - mlflow: kubas_cluster

user: ???

reporter:
  save: ???
  background: ???
  title: ???
  mask_retrievers: []
  metrics_run_ids: []
  template_asset_path: report_template.html

metadata:
  user: ${user}
  experiment_name: ???
  run_name: ???
  description: ???
