defaults:
  - save: mlflow_standalone_run

title: Ulcerative Colitis Preprocessing - KNL Patos

background:
  _target_: report.masks.BasicImageRetriever
  source_dir: /mnt/data/KNL_PATOS/colon/IBD_AI
  globs:
    - "*.czi"
  layer_name: Ulcerative Colitis

mask_retrievers:
  - _target_: report.masks.RunIDMlflowMaskRetriever
    run_id: 8ef6d6f0c9af4f35a087596960f675aa
    dir_name: tissue_masks
    layer_name: Tissue mask
    shader_conf:
      type: heatmap
      opacity: 0.5
      color: "#ffff00"
      visible: False

  - _target_: report.masks.RunIDMlflowMaskRetriever
    run_id: 75fc3e53112f4634ae5238777d87e88c
    dir_name: blur_per_pixel
    layer_name: Blur
    shader_conf:
      type: heatmap
      opacity: 0.5
      color: "#00ffff"
      visible: False

  - _target_: report.masks.RunIDMlflowMaskRetriever
    run_id: 75fc3e53112f4634ae5238777d87e88c
    dir_name: artifacts_per_pixel 
    layer_name: Residual artifacts
    shader_conf:
      type: heatmap
      opacity: 0.5
      color: "#00ffff"
      visible: False

  - _target_: report.masks.RunIDMlflowMaskRetriever
    run_id: 4775c5688189427e803a154a213acb0e
    dir_name: tile_masks/clean_tiles
    layer_name: Used Tiles
    shader_conf:
      type: heatmap
      opacity: 1.0
      color: "#00ff00"
      visible: False

  - _target_: report.masks.RunIDMlflowMaskRetriever
    run_id: 4775c5688189427e803a154a213acb0e
    dir_name: tile_masks/blur_tiles
    layer_name: Blur Tiles
    shader_conf:
      type: heatmap
      opacity: 1.0
      color: "#ff0000"
      visible: False

  - _target_: report.masks.RunIDMlflowMaskRetriever
    run_id: 4775c5688189427e803a154a213acb0e
    dir_name: tile_masks/artifacts_tiles
    layer_name: Artifacts Tiles
    shader_conf:
      type: heatmap
      opacity: 1.0
      color: "#ff0000"
      visible: False

save:
  metadata:
    experiment_name : 'Ulcerative Colitis'
    run_name : '📊 Report: Preprocessing - knl patos'
    description: Report