# @package _global_

model: virchow2
output_dir: ${project_dir}/embeddings/${dataset.institution}
concurrency: 128
block_size: 128
rows_per_file: 50000

metadata:
  run_name: "🔢 Embeddings: ${dataset.institution}"
  description: Tile embeddings for ${dataset.institution} using model ${model}
  hyperparams:
    model: ${model}
    concurrency: ${concurrency}
    block_size: ${block_size}
    rows_per_file: ${rows_per_file}
