# @package _global_

model: virchow2
output_dir: ${project_dir}/embeddings/${dataset.institution}
concurrency: 1024
batch_size: 256

metadata:
  run_name: "🔢 Embeddings: ${dataset.institution}"
  description: Tile embeddings for ${dataset.institution} using model ${model}
  hyperparams:
    model: ${model}
    concurrency: ${concurrency}
    batch_size: ${batch_size}
