mlflow_uris:
  nancy_high: mlflow-artifacts:/86/55fc9f4d8e98449dbf533f582839c489/artifacts/predictions.json
  nancy_low: mlflow-artifacts:/86/b0e9ea26050e48c4a13e5d36ef6c93e7/artifacts/predictions.json
  neutrophils: mlflow-artifacts:/86/5c3bffbd842f4a6f983b7ce67707aca3/artifacts/predictions.json
