mlflow_uris:
  nancy_high:
    1/5: ...
    2/5: ...
    3/5: ...
    4/5: ...
    5/5: ...
    final: ...
  nancy_low:
    1/5: ...
    2/5: ...
    3/5: ...
    4/5: ...
    5/5: ...
    final: ...
  neutrophils:
    1/5: ...
    2/5: ...
    3/5: ...
    4/5: ...
    5/5: ...
    final: ...
