defaults:
  - /dataset/processed_w_masks/ikem_validation@_here_
  - _self_

mlflow_uris:
  tiling:
    predict: mlflow-artifacts:/86/ef20b95b9e9348de9e4ca81597b3447a/artifacts/predict - ikem_validation