defaults:
  - /dataset/processed_w_masks/knl_patos@_here_
  - _self_

mlflow_uris:
  tiling:
    test_preliminary: mlflow-artifacts:/86/d57c09bc02914ff58ba659b91f34c469/artifacts/test_preliminary - knl_patos
    test_final: mlflow-artifacts:/86/d57c09bc02914ff58ba659b91f34c469/artifacts/test_final - knl_patos