# @package _global_

n_resamples: 2000
confidence_level: 0.95
seed: 42

metadata:
  run_name: "📍 Location Metrics: ${dataset.institution}"
  description: Slide-level ensembling metrics stratified by location with case-level bootstrap confidence intervals for ${dataset.institution}
  hyperparams:
    n_resamples: ${n_resamples}
    confidence_level: ${confidence_level}
    seed: ${seed}
